### ISSUE TITLE
Zooming scroll view does not accept swipe when zoomed and reused. 

### ISSUE THREAD

**Issue by lightandshadow68** [Blue-Rocket/BRScroller#1] opened 2015-10-23 16:04 UTC
I'm running into an issue where pages that were zoomed often do not accept swipes to scroll to the next page when they are reused. I can swipe on the "black bars" above and below the image, but swiping on the image does not cause the outer scroll view to scroll. 

Is there something I need to do to reset the zooming scroll page before it is reused?

**Comment by msqr** [comment] 2015-10-23 17:58
Are you resetting the zoom level back to 1 when you update the reusable page content? The BRScrollerDemo's `AsyncPhotoViewController` and `PdfViewController` examples are both cases where the page views are scroll views, which sounds similar to your setup. They both end up calling something along the lines of

``` objc
[pageScrollView setZoomScale:1 animated:NO];
```

when the content is updated for a page.

**Comment by lightandshadow68** [comment] 2015-10-23 18:29
I've implemented the scroller:willDisplayPage:view as follows. However, the content area with the photo does not scroll when swiped. 

```
- (void)scroller:(BRScrollerView *)scroller
 willDisplayPage:(NSUInteger)index
            view:(UIView *)reusablePageView {
    BRZoomingImageView *zoomer = (BRZoomingImageView *)reusablePageView;
    zoomer.tag = index;
    [zoomer setZoomScale:1.0 animated:NO];
    MyModel *model = _models[index];
    zoomer.imageView.imageURL = [NSURL URLWithString:model.remoteURL];
}
```

Is this the right delegate method?

The image is at the correct size when reused, it just does not scroll when swiped. My current theory is that it has something to do with a gesture recognizer intercepting touches or a view blocking them. However, I haven't been able to figure out exactly what prevents the swipe from working on the image content.

**Comment by msqr** [comment] 2015-10-26 17:55
That is the right delegate method, yes, and looks like you're doing the same as the [demo](https://github.com/Blue-Rocket/BRScroller/blob/master/BRScrollerDemo/BRScrollerDemo/AsyncPhotoViewController.m) so that all looks fine. Have you run that demo, and does the demo work OK for you on the same device you're testing on? What does your `createReusablePageViewForScroller:` implementation look like?

**Comment by lightandshadow68** [comment] 2015-11-02 14:57
Currently, it looks like 

```
static int colorIndex = 0;

- (UIView *)createReusablePageViewForScroller:(BRScrollerView *)scroller 
{   
    NSLog(@"Color Index: %d", colorIndex);

    UIColor *bgColor = nil;

    switch (colorIndex) {

        case 0:
            bgColor = [UIColor redColor];
            break;
        case 1:
            bgColor = [UIColor greenColor];
            break;
        case 2:
            bgColor = [UIColor blueColor];
            break;
        case 3:
            bgColor = [UIColor purpleColor];
            break;
        case 4:
            bgColor = [UIColor orangeColor];
            break;
    }

    BRZoomingImageView *zoomer = [[BRZoomingImageView alloc] initWithFrame:scroller.bounds];
    zoomer.imageView.delegate = self;
    zoomer.scrollDelegate = self;
    zoomer.imageView.imageContentView.delegate = self;
    zoomer.directionalLockEnabled = YES;
   // zoomer.doubleTapToZoom = YES;
    zoomer.backgroundColor = bgColor;
    zoomer.showsVerticalScrollIndicator = NO;
    zoomer.showsHorizontalScrollIndicator = NO;

    colorIndex++;
    if (colorIndex > 4) {
        colorIndex = 0;
    }
    return zoomer;
}
```

I was able to correlate between having previously zoomed the view and loosing swipe functionality when refused by setting them to have different background colors.

First, I disabled user interaction on everything but the zooming scroll view. this didn't seem to have any effect. Next I added...

```
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    NSLog(@"Touches began in zooming scroll view");
    [super touchesBegan:touches withEvent:event];
}
```

To the zooming scroll view. The zooming scroll view receives touchesBegan:withEvent: calls when swiping fails, which indicates the gesture recognizer is not receiving touches. 

On a hunch, I completely commented out gestureRecognizer:shouldReceiveTouch: in BRCenteringScrollView as swipes in the non-image areas continued to work even if the previous page had been zoomed. However, this still did not solve the problem. 

If I add....

```
-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    return YES;
}
```

This allows both scroll views to scroll at the same time, but the main scroll view scrolls along with the image scroll view, which is not the desired behavior. 

So, it seems the scroll views gesture recognizer is not receiving touch events after a reused page is zoomed.

**Comment by lightandshadow68** [comment] 2015-11-02 16:30
"That is the right delegate method, yes, and looks like you're doing the same as the demo so that all looks fine. Have you run that demo, and does the demo work OK for you on the same device you're testing on?"

The demo runs correctly across devices and simulators. The issue I'm seeing is consistent across both as well. My use case is differs in that both preview and full resolution images are remote, rather than local. This does not seem to be a good fit as the delegate methods of`renderPreviewImageForView:key:atSize:` and `previewImageForView:atSize:` expect `UIImages` to be returned at the end of the method call.

**Comment by lightandshadow68** [comment] 2015-11-03 07:48
After digging deeper, I've discovered that zoomed reused pages receive calls to `touchesBegan:` after the custom accessor `setContentOffset:` is called on `BRCenterScrollingView`. If the page has not been previously zoomed, `touchesBegan` is not called on the zooming scroll view. Commenting out `setContentOffset:` results in the image hugging the upper left corner of the scroll view, but scrolling works even after zooming. 

```
2015-11-03 02:14:12.570 appName[74455:18662704] touchesMoved >>>>>>>> 
2015-11-03 02:14:12.570 appName[74455:18662704] <UIScrollViewDelayedTouchesBeganGestureRecognizer: 0x7f8e3a4bd5f0; state = Possible; delaysTouchesBegan = YES; view = <BRZoomingImageView 0x7f8e3b0aa000>; target= <(action=delayed:, target=<BRZoomingImageView 0x7f8e3b0aa000>)>>
2015-11-03 02:14:12.570 appName[74455:18662704] <UIScrollViewPanGestureRecognizer: 0x7f8e3a44e4e0; state = Possible; delaysTouchesEnded = NO; view = <BRZoomingImageView 0x7f8e3b0aa000>; target= <(action=handlePan:, target=<BRZoomingImageView 0x7f8e3b0aa000>)>>
2015-11-03 02:14:12.571 appName[74455:18662704] <UIScrollViewPinchGestureRecognizer: 0x7f8e3a5b30f0; state = Possible; delaysTouchesEnded = NO; view = <BRZoomingImageView 0x7f8e3b0aa000>; target= <(action=handlePinch:, target=<BRZoomingImageView 0x7f8e3b0aa000>)>>
```

What seems odd is that the same content offset is being reported when the page is first displayed (and scrolling works) and when reused (and scrolling no longer works). What's different is that the zooming image view receives touchesBegan which, AFAIK, should not occur due to `the UIScrollViewDelayedTouchesBeganGestureRecognizer`

**Comment by msqr** [comment] 2015-11-03 16:50
I am curious what ends up being different in the way your app is running versus the demo app (which works OK). Perhaps there is something to the use of remote images, but I'm not quite sure. The image preview methods are called from background threads, are you by chance manipulating any of the view hierarchy in those callbacks?

Do you have a small stand-alone app that demonstrates the problem that you could share? Even if you just forked the repo and added a new example to the demo app that exhibited the problem, that would be very helpful for investigating the cause of the issue.

**Comment by lightandshadow68** [comment] 2015-11-09 14:42
I have wrapped calls that access the view hierarchy in GCD blocks running on the main queue, so I don't suspect that is the issue.

I do not have a stand alone at to demo at this time. Ended up moving to a custom UIPagingViewController solution due to time constraints.

**Comment by msqr** [comment] 2015-11-17 20:51
OK, I'll close this ticket then as I don't have a reproducible test case.

**Closed as completed by msqr** 2015-11-17 20:51 UTC
